name: Automating Weather Data Collection

on:
  schedule:
    - cron: '0 10 * * *'  # This makes it run daily at 10 AM UTC
  workflow_dispatch:  # This allows me to run it manually for testing purposes

jobs:
  weather_data:
    runs-on: ubuntu-latest  # This uses the Ubuntu virtual machine for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This clones my repository into the virtual machine to allow me to work with it.

    - name: Make weather.sh executable and run the script
      run: |
        chmod u+x ./weather.sh  # This makes the script executable (otherwise it would request permissions)
        ./weather.sh  # This executes the script I created previously

    - name: Commit and push new weather data
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/weather/*
        git


